Initial Setup
nossas/bonde-migrations pull request #1
Opened 2018-07-31 21:34 UTC by hudsama

#### Repo responsável pelo gerenciamento das `migrations` e `database` do bonde.

> Initial
- Adicionado o `diesel` (lib responsável pela manipulação das migrations
- Criada `migration` inicial (contém toda a estrutura inicial do database | baseado no atual schema)
- Adicionado arquivo .env.sample para possíveis configurações

##### TODO
- [ ] Create Dockerfile
- [ ] Config to deploy
- [ ] Adds and run sql-specs in this repo

2018-07-31 22:09 UTC, lpirola requested changes
Vale adicionar como tarefa, modificar o bonde-install para usar esse novo formato.

Assim ficará mais fácil de testar por outros desenvolvedores.

2018-07-31 23:02 UTC, lpirola commented
A estratégia de deploy para produção precisa ser prevista.

2018-08-01 13:37 UTC, lpirola commented
@hudsama o drone não adicionou o hook no github, ficou faltando ver isso. Além de adicionar as specs. 

Você chegou a pensar como incluir as specs por aqui?

2018-08-01 16:39 UTC, hudsama commented
@lpirola criei uma task para adicionar ao bonde-install.
Referente ao testes será parecido com o de sql do `bonde-server`, teremos uma pasta `sql-specs` nesse mesmo repo e um `alias` que ira criar um banco de teste (baseado nas migrations) e rodar os sql specs.

2018-08-06 19:07 UTC, hudsama commented
Updates:
- Atualizado dockerfile
- adicionado comandos para rodar usando docker
- adicionado env `--database-url` no lugar do .env
- adicionado sql-specs iniciais e comandos para rodar os specs.

### pendencias:
> A parte de rodar os testes ta bem manual ainda, irei criar um script ou makefile para facilitar isso.
Criação do banco e rodar os specs.

- verificar o motivo dos commits/etc não estarem indo pro CI.
- corrigir .drone.yml
- documentar estratégia de deploy

2018-08-06 21:24 UTC, hudsilva commented
@lpirola adicionei os testes rodando a partir de um script. 
Atualizei o readme explicando como executar. (o script cria o data e as migrations antes de rodar os tests)

ficando pendente agora o problema do CI, e a integração com o bonde-install.

2018-08-07 12:55 UTC, lpirola commented
@hudsama o drone está rolando! https://ci.bonde.org/nossas/bonde-migrations

2018-08-07 12:57 UTC, lpirola approved these changes

2018-08-07 12:57 UTC, merged