feat: create a hub of settings module community
nossas/bonde-migrations pull request #53
Opened 2020-04-02 14:26 UTC by igr-santos

2020-04-02 19:48 UTC, lpirola requested changes

2020-04-02 19:48 UTC, lpirola commented on migrations/2020-04-02-112331_add_app_settings/down.sql
> +DROP TABLE public.app_settings;
achei o nome app_settings ruim :/

outras possibilidades?

2020-04-02 19:48 UTC, lpirola commented on migrations/2020-04-02-112331_add_app_settings/down.sql
> +DROP TABLE public.app_settings;
community_settings?

2020-04-02 19:48 UTC, lpirola commented on migrations/2020-04-02-112331_add_app_settings/up.sql
> +    community_id bigint NOT NULL,
ainda mais por essa ligação!

2020-04-13 15:08 UTC, vivianedias commented on migrations/2020-04-02-112331_add_app_settings/down.sql
> +DROP TABLE public.app_settings;
acho que vale mudar pra community_settings!

2020-04-13 15:09 UTC, vivianedias requested changes
acredito que apenas revisar o nome da tabela, como já foi mencionado nos comentários

2020-04-16 17:02 UTC, lpirola commented
@igr-santos falta alterar o nome da tabela, não?

2020-04-16 18:19 UTC, merged